name: Debug SSH Key

on:
  push:
    branches:
      - master

jobs:
  debug-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Print SSH Key Length
        run: |
          echo "SSH Key length: $(echo "${{ secrets.SSH_KEY }}" | wc -c) characters"
          # This will safely print the length without exposing the actual key